<div id="menu">
                        <div id="header3">
                            <ul class="nav2">
                                    <li><a href="<?php echo BASE_URL; ?>">Inicio</a></li>
                                    <li><a href="">Proyecto</a>
                                        <ul>
                                            <li><a href="<?php echo BASE_URL . 'proyecto'; ?>">Mostrar Proyectos</a></li>
                                            <li><a href="<?php echo BASE_URL . 'proyecto/nuevo'; ?>">Agregar Proyecto</a></li>
                                        </ul>
                                    </li>
                                    
                                    </li>
                                    <li><a href="">Modelo</a>
                                        <ul>
                                            <li><a href="<?php echo BASE_URL . 'modelos'; ?>">Mostrar Modelos</a></li>
                                            <li><a href="<?php echo BASE_URL . 'modelos/nuevo'; ?>">Agregar Modelo</a></li>
                                        </ul>
                                    </li>

                                    <li><a href="<?php echo BASE_URL; ?>">Reportes</a>

                                        <ul>
                                            <li><a href="<?php echo BASE_URL . 'reporte/estado'; ?>">Coord. Estado</a></li>
                                            <li><a href="<?php echo BASE_URL . 'reporte/nacion'; ?>">Coord. Nacional</a></li>
                                        </ul>

                                    </li>
                                </ul>
                                
                        </div>
                </div>