

    <h3>editar equipo</h3>
    <form method="post" action="<?php echo BASE_URL; ?>equipo/editar/<?php echo $this->datos['id_equipo']; ?>">
        <input type="hidden" name="guardar" value="1" />
    <table>
        <tr>
            <td>
                <label>id equipo</label>
            </td>
        </tr>
        <tr>
            <td>
                <input type='text' name='id_equipo' id="id_equipo" maxlength="8" value="<?php if (isset($this->datos['id_equipo'])) echo $this->datos['id_equipo']; ?>" readonly>
            </td>
        </tr>
        <tr>
            <td>
                <LABEL>nombre del material</LABEL>
            </td>
        </tr>
        <tr>
            <td>
                <textarea name="nombre" rows="2" cols="80" class='largo' ><?php if (isset($this->datos['nombre'])) echo $this->datos['nombre'] ?></textarea>
            </td>
        </tr>
        
        <tr>
            <td>
                <label>tipo de equipo</label>
            </td>
        </tr>
        <tr>
            <td>
                <input type='text' name='unidad' id="id_materiales" maxlength="8" value="<?php if (isset($this->datos['unidad'])) echo $this->datos['unidad']; ?>" autocomplete="off">
            </td>
        </tr>
        
        <tr>
            <td>
                <label>COP</label>
            </td>
        </tr>
        <tr>
            <td>
                <input type='text' name='cop' id="cop" class="numerico" maxlength="12" value="<?php if (isset($this->datos['COP'])) echo $this->datos['COP']; ?>" autocomplete="off">
            </td>
        </tr>
        
        <tr>
            <td>
                <label>precio</label>
            </td>
        </tr>
        <tr>
            <td>
                <input type='text' name='precio' id="precio" class="numerico" maxlength="12" value="<?php if (isset($this->datos['precio'])) echo $this->datos['precio']; ?>" autocomplete="off">
            </td>
        </tr>
        
        <tr>
            <td>
                    <input type='submit' value='editar' class="btn btn-otro">
		
            </td>
        </tr>
    </table>
    </form>
