                        <div id="header3">
                            <ul class="nav2">
                                    <li><a href="<?php echo BASE_URL; ?>">Inicio</a></li>
                                    
                                    <li><a href="<?php echo BASE_URL . 'proyecto'; ?>">Proyectos En Ejecucion</a></li>
                                    <li><a href="">Proyectos Culminados</a></li>
                                    <li><a href="<?php echo BASE_URL . 'reporte/estado'; ?>">Informe Mensual</a></li>
                                    

                                </ul>
                                
                        </div>
