                        <div id="header3">
                            <ul class="nav2">
                                    <li><a href="<?php echo BASE_URL; ?>">Inicio</a></li>
                                    <li><a href="">Proyecto</a>
                                        <ul>
                                            <li><a href="<?php echo BASE_URL . 'proyecto'; ?>">Mostrar Proyectos</a></li>
                                            <li><a href="<?php echo BASE_URL . 'proyecto/nuevo'; ?>">Agregar Proyecto</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="">Partida</a>
                                        <ul>
                                            <li><a href="<?php echo BASE_URL . 'partida'; ?>">Mostrar Partidas</a></li>
                                            <li><a href="<?php echo BASE_URL . 'proyecto/nuevo'; ?>">Agregar Partida</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="">Modelo</a>
                                        <ul>
                                            <li><a href="<?php echo BASE_URL . 'modelos'; ?>">Mostrar Modelos</a></li>
                                            <li><a href="<?php echo BASE_URL . 'modelos/nuevo'; ?>">Agregar Modelo</a></li>
                                        </ul>
                                    </li>

                                    <li><a href="">Material</a>
                                        <ul>
                                            <li><a href="<?php echo BASE_URL . 'material/listar'; ?>">Mostrar Materiales</a></li>
                                            <li><a href="<?php echo BASE_URL . 'material/agregar'; ?>">Agregar Material</a></li>
                                        </ul>
                                    </li>

                                    <li><a href="">Equipo</a>
                                        <ul>
                                            <li><a href="<?php echo BASE_URL . 'equipo/listar'; ?>">Mostrar Equipo</a></li>
                                            <li><a href="<?php echo BASE_URL . 'equipo/agregar'; ?>">Agregar Equipo</a></li>
                                        </ul>
                                    </li>

                                    <li><a href="">Mano de Obra</a>
                                        <ul>
                                            <li><a href="<?php echo BASE_URL . 'mano/listar'; ?>">Mostrar Mano de Obra</a></li>
                                            <li><a href="<?php echo BASE_URL . 'mano/agregar'; ?>">Agregar Mano de Obra</a></li>
                                        </ul>
                                    </li>
                                    
                                </ul>
                                
                        </div>
