
    <h3>editar mano de obra</h3>
    <form method="post" action="<?php echo BASE_URL; ?>mano/editar/<?php echo $this->datos['id_mano']; ?>">
        <input type="hidden" name="guardar" value="1" />
    <table>
        <tr>
            <td>
                <label>id mano de obra</label>
            </td>
        </tr>
        <tr>
            <td>
                <input type='text' name='id_mano' id="id_mano" maxlength="8" value="<?php if (isset($this->datos['id_mano'])) echo $this->datos['id_mano']; ?>" readonly>
            </td>
        </tr>
        <tr>
            <td>
                <LABEL>nombre del material</LABEL>
            </td>
        </tr>
        <tr>
            <td>
                <textarea name="nombre" rows="2" cols="80" class='largo' ><?php if (isset($this->datos['nombre'])) echo $this->datos['nombre'] ?></textarea>
            </td>
        </tr>
        
        <tr>
            <td>
                <label>unidad</label>
            </td>
        </tr>
        <tr>
            <td>
                <input type='text' name='unidad' id="unidad" maxlength="8" value="<?php if (isset($this->datos['unidad'])) echo $this->datos['unidad']; ?>" autocomplete="off">
            </td>
        </tr>
        
        <tr>
            <td>
                <label>precio actual</label>
            </td>
        </tr>
        <tr>
            <td>
                <input type='text' name='jornal' id="jornal" class="numerico" maxlength="8" value="<?php if (isset($this->datos['jornal'])) echo $this->datos['jornal']; ?>" autocomplete="off">
            </td>
        </tr>
        
        <tr>
            <td>
                    <input type='submit' value='editar' class="btn btn-otro">
		
            </td>
        </tr>
    </table>
    </form>