<h3><?php if ($this->mensaje) echo $this->mensaje; ?></h3>
<p> </p>

<a href="<?php echo BASE_URL;?>">Ir al Inicio</a> |
<a href="javascript: history.back(1)">Volver a la Pagina Anterior</a>

<?php if (!Session::get('autenticado')): ?>

| <a href="<?php echo BASE_URL . 'login';?>">Iniciar Session</a>

<?php endif;  

	if (!Session::get('autenticado')){
	    include('./views/login/index.phtml');
	}



?>

