
    <h3>cargar imagenes de la valuacion</h3>
<div class="center">
<form id="clave" method="post" action="" enctype="multipart/form-data">
<input type="hidden" name="guardar" value="1">
     
        <p>
          <label for="vieja">selecciones las imagenes:</label>
          <input type="file" name="file[]" multiple="multiple" style="width:350px; background:gray;" />
        </p>
          
        <p>
          <input type="submit" class="btn btn-otro" value="cargar" />
        </p>

</form>

</div>