<h2>Activacion de cuenta de usuario</h2>

<p> </p>

<a href="<?php echo BASE_URL;?>">Ir al Inicio</a>
    
<?php if(!Session::get('autenticado')): ?>
    
    | <a href="<?php echo BASE_URL; ?>login">Iniciar Sesion</a>
    
<?php endif; ?>
</div>
<div id="fondo">
<img src="<?php echo BASE_URL;?>views/layout/layout3/img/fondo.png" width="1024px" heigth="800px"></img>
    </div>
    <div id="login">
        <form name="form1" method="post" action="<?php echo BASE_URL; ?>login">
        <div id="iniciar">
            
        
            <span class="iniciar">iniciar sesi&oacuten</span>
            <input type="hidden" name="enviar" value="1">                
                <br />
                <input type="email" name="email" class="inputredondo" autocomplete="off" value="<?php if (isset($this->datos)) echo $this->datos['email'];  ?>" placeholder="Email">                
                <br />
                <input type="password" name="pass" class="inputredondo"  placeholder="Contraseña" value="">

        
        
        </div>
        <div id="captcha">
            <img  src="<?php echo BASE_URL; ?>views/login/captcha.php"><br />
            <input type="text" name="captcha" class="inputredondo numerico"  placeholder="Numeros de la Imagen" autocomplete="off">
        </div>

        <div id="enviar">
            <input type='submit' value='entrar' class="btn btnentrar">
            
        </div>

        </form>
    </div>

<style type="text/css">

#footer, #atras, #menu{
    display: none;
}

#fondo{
    margin-top: -98px;
}



</style>