
    <h3>cambiar imagen de perfil</h3>
<form name="form1" method="post" action="<?php echo BASE_URL; ?>registro/change/<?php if(isset($this->datos)) echo $this->datos['id']; ?>" enctype="multipart/form-data">
<input type="hidden" name="guardar" value="1">
<input type="hidden" name="cedula" value="<?php if($this->datos['cedula'] != '') {echo $this->datos['cedula'];} ?>">
<input type="hidden" name="ruta" value="views/registro/imagenes">
<input type="hidden" name="imagen" value="<?php if($this->datos['foto'] != '') {echo $this->datos['foto'];} ?>">
<table class="lista">
	<thead>
		<td width="100px">imagen actual</td>
        <td width="100px">nueva imagen</td>
	</thead>

    <tr>
        <td>

            <div>
                <img src="<?php echo BASE_URL;?>views/registro/imagenes/<?php if($this->datos['foto'] != '') {echo $this->datos['foto'];} if($this->datos['foto'] == '') {echo 'default.jpg';} ?>" width="150px" height="150px"><br>
                 
            </div>

        </td>

        <td>

            <div id="list">
                <img id="imagen" src="<?php echo BASE_URL;?>views/registro/imagenes/default.jpg" width="150px" height="150px"><br>
                 
            </div>           

        </td>

    </tr>
    <tr>
        <td colspan="2"><input type="file" name="files" id="files" style="width: 100px !important;"></td>

    </tr>
    <tr>
        <td colspan="2"><input type="submit" class="btn btn-otro" value="cambiar"></td>

    </tr>
</table>

</form>
<script>
  function handleFileSelect(evt) {



    var files = evt.target.files; // FileList object

    // Loop through the FileList and render image files as thumbnails.
    for (var i = 0, f; f = files[i]; i++) {

      // Only process image files.
      if (!f.type.match('image.*')) {
        continue;
      }

      var reader = new FileReader();

      // Closure to capture the file information.
      reader.onload = (function(theFile) {
        return function(e) {
          // Render thumbnail.
          var span = document.createElement('span');
          span.innerHTML = ['<img class="thumb" src="', e.target.result,
                            '" title="', escape(theFile.name), '"/>'].join('');
          document.getElementById('list').insertBefore(span, null);
        };
      })(f);

      // Read in the image file as a data URL.
      reader.readAsDataURL(f);
    }
  }

  document.getElementById('files').addEventListener('change', handleFileSelect, false);
</script>