
    <h3>cambiar la clave de acceso</h3>
<div class="center">
<form id="clave" method="post" action="<?php echo BASE_URL; ?>registro/password/<?php if(isset($this->datos)) echo $this->datos['id']; ?>">
<input type="hidden" name="guardar" value="1">
<table>

<tr>
    <td>      
        <p>
          <label for="vieja">intruduzca su clave actual</label>
          <input type="password" id="vieja" name="vieja" autocompleted="off" />
        </p>
    </td>
</tr>     
<tr>
    <td>            
        <p>
          <label for="nueva">intruduzca su nueva clave</label>
          <input type="password" id="nueva" name="nueva" autocompleted="off" />
        </p>
    </td>
</tr>
<tr>
    <td>       
        <p>
          <label for="confirmar">confirmar su nueva clave</label>
          <input type="password" id="confirmar" name="confirmar" autocompleted="off" />
        </p>
    </td>
</tr>
<tr>
    <td>          
      <p>
        <input type="submit" class="btn btn-otro" value="cambiar" />
      </p>
    </td>
</tr>
</form>
</table>
</div>
