    <h3>Resumen De Avance En El Estado</h3>

        <table class="lista">
            <thead>
            <tr>
                <td width="150px">viviendas</td>
                <td width="150px">cantidad</td>
                <td width="500px">grafico</td>
            </tr>  
            </thead>

            <tr>
                <td><label>culminadas</label></td>
                <td><label>100</label></td>
                <td rowspan="3"><img  src="<?php echo BASE_URL; ?>views/reporte/estado.php"></td>
            </tr>

            <tr>
                <td><label>por culminar</label></td>
                <td><label>100</label></td>                
            </tr>    

            <tr>
                <td><label>sin iniciar</label></td>
                <td><label>100</label></td>                
            </tr>

            <tr>
                <td><label>totalde viviendas para el año</label></td>
                <td><label>100</label></td>                
            </tr>      

        </table>

        <h3>Resumen De Avance Por Etapas En El Estado</h3>

        <table class="lista">
            <thead>
            <tr>
                <td width="50px">etapa</td>
                <td width="200px">descripcion</td>
                <td width="50px">cantidad</td>
                <td width="500px">grafico</td>
            </tr>  
            </thead>

            <tr>
                <td><label>1RA</label></td>
                <td><label>Losa de Fundación.</label></td>
                <td><label>45</label></td>
                <td rowspan="5"><img  src="<?php echo BASE_URL; ?>views/reporte/etapas_estado.php"></td>
            </tr>

            <tr>
                <td><label>2DA</label></td>
                <td><label>Estructura y Techo.</label></td>
                <td><label>65</label></td>                
            </tr>    

            <tr>
                <td><label>3RA</label></td>
                <td><label>Levantamiento de Paredes.</label></td>
                <td><label>90</label></td>                
            </tr>

            <tr>
                <td><label>4TA</label></td>
                <td><label>Acabados y colocación de accesorios.</label></label></td>
                <td><label>120</label></td>                
            </tr>

            <tr>
                <td><label>5TA</label></td>
                <td><label>Instalación de Puertas y Ventanas; Pintura y Servicios Básicos.</label></td>
                <td><label>230</label></td>                
            </tr>

            <tr>
                <td colspan=2><label>totalde viviendas para el año</label></td>
                <td><label>550</label></td>                
            </tr>      

        </table>
        <br />